In [4]:
# This is used to tell google collaborate to use Tenserflow
%tensorflow_version 2.x

In [6]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# Tensor
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape.


In [11]:
# Creating Tenser (vector)
tf.Variable(["1", "2", "3"], tf.string)

<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'1', b'2', b'3'], dtype=object)>

# Tensor Basics

### Degree/Rank
The number of dimensions in a tensor. In other words, number of lists within a tensor.

```
tf.rank(tensor)
```

### Shape
Number of elements in a dimension.
```
tensor.shape
```

In [16]:
# Reshaping of Tensor
tensor1 = tf.ones(shape=[1, 2, 3])
print(tensor1)
tf.reshape(tensor1, shape=[1, 3, 2]) # reshaping tensor1
tf.reshape(tensor1, [3, -1]) # -1 tells tensor to calculate the size of the dimension in that
                             # place this will reshape tensor to [3, 2]

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

# Types of Tensors

* Variable
* Constant
* Placeholder
* SparseTensor

All tensors except `Variable` are immutable.